spring.application.name=hello-world-spring
spring.datasource.url=jdbc:h2:mem:helloworlddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8081
